import { NextResponse } from 'next/server'
import connectDB from '@/lib/mongodb'
import Car from '@/models/car'

const carData = [
	{
		brand: 'BMW',
		modelName: '3 Series',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 850,
		images: [
			'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&h=600&fit=crop',
		],
		description: 'Luxury sedan with premium features and exceptional performance. Perfect for business trips or special occasions.',
		features: ['GPS Navigation', 'Leather Seats', 'Bluetooth', 'Backup Camera', 'Sunroof', 'Heated Seats'],
		location: 'Athens',
		isAvailable: true,
		averageRating: 4.8,
		totalReviews: 24,
		mileage: 15000,
		color: 'Black',
		licensePlate: '34ABC123',
		carType: 'luxury',
	},
	{
		brand: 'Mercedes',
		modelName: 'C-Class',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'hybrid',
		seats: 5,
		pricePerDay: 950,
		images: [
			'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1617531653520-bd788a3a0c73?w=800&h=600&fit=crop',
		],
		description: 'State-of-the-art hybrid luxury sedan with cutting-edge technology and unmatched comfort.',
		features: ['GPS Navigation', 'Leather Seats', 'Bluetooth', 'Parking Sensors', 'Panoramic Sunroof', 'Ambient Lighting'],
		location: 'Thessaloniki',
		isAvailable: true,
		averageRating: 4.9,
		totalReviews: 31,
		mileage: 8000,
		color: 'Silver',
		licensePlate: '34XYZ789',
		carType: 'luxury',
	},
	{
		brand: 'Toyota',
		modelName: 'Corolla',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 450,
		images: [
			'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop',
		],
		description: 'Reliable and fuel-efficient sedan, ideal for daily commutes and city driving.',
		features: ['GPS Navigation', 'Bluetooth', 'Backup Camera', 'USB Charging', 'Air Conditioning'],
		location: 'Heraklion',
		isAvailable: true,
		averageRating: 4.5,
		totalReviews: 42,
		mileage: 25000,
		color: 'White',
		licensePlate: '06DEF456',
		carType: 'sedan',
	},
	{
		brand: 'Honda',
		modelName: 'Civic',
		year: 2022,
		transmission: 'manual',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 400,
		images: [
			'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop',
		],
		description: 'Sporty and economical sedan with manual transmission for driving enthusiasts.',
		features: ['Bluetooth', 'USB Charging', 'Air Conditioning', 'Cruise Control'],
		location: 'Patras',
		isAvailable: true,
		averageRating: 4.3,
		totalReviews: 18,
		mileage: 35000,
		color: 'Blue',
		licensePlate: '35GHI789',
		carType: 'sedan',
	},
	{
		brand: 'Volkswagen',
		modelName: 'Golf',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'diesel',
		seats: 5,
		pricePerDay: 500,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'Compact hatchback with excellent fuel economy and comfortable interior.',
		features: ['GPS Navigation', 'Bluetooth', 'Parking Sensors', 'Dual Climate Control', 'Apple CarPlay'],
		location: 'Rhodes',
		isAvailable: true,
		averageRating: 4.6,
		totalReviews: 28,
		mileage: 18000,
		color: 'Gray',
		licensePlate: '34JKL012',
		carType: 'hatchback',
	},
	{
		brand: 'Audi',
		modelName: 'Q5',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'diesel',
		seats: 5,
		pricePerDay: 1100,
		images: [
			'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&h=600&fit=crop',
		],
		description: 'Premium SUV with spacious interior and advanced safety features.',
		features: ['GPS Navigation', 'Leather Seats', 'Bluetooth', '360 Camera', 'Heated Seats', 'Adaptive Cruise Control'],
		location: 'Santorini',
		isAvailable: true,
		averageRating: 4.9,
		totalReviews: 36,
		mileage: 12000,
		color: 'Black',
		licensePlate: '34PQR678',
		carType: 'suv',
	},
	{
		brand: 'Tesla',
		modelName: 'Model 3',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'electric',
		seats: 5,
		pricePerDay: 1200,
		images: [
			'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&h=600&fit=crop',
		],
		description: 'Cutting-edge electric sedan with autopilot and impressive range.',
		features: ['Autopilot', 'Premium Audio', 'Glass Roof', 'Over-the-air Updates', 'Supercharging Network', '15-inch Touchscreen'],
		location: 'Athens',
		isAvailable: true,
		averageRating: 4.9,
		totalReviews: 45,
		mileage: 5000,
		color: 'White',
		licensePlate: '34YZA567',
		carType: 'sedan',
	},
	{
		brand: 'Porsche',
		modelName: '911',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 4,
		pricePerDay: 2500,
		images: [
			'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=800&h=600&fit=crop',
		],
		description: 'Iconic sports car delivering thrilling performance and timeless design.',
		features: ['Sport Chrono Package', 'Leather Interior', 'BOSE Sound System', 'Active Suspension', 'Launch Control', 'Carbon Fiber Trim'],
		location: 'Mykonos',
		isAvailable: true,
		averageRating: 5.0,
		totalReviews: 12,
		mileage: 3000,
		color: 'Red',
		licensePlate: '34BCD890',
		carType: 'sports',
	},
	{
		brand: 'Hyundai',
		modelName: 'Tucson',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 650,
		images: [
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
		],
		description: 'Modern SUV with striking design and comprehensive safety package.',
		features: ['GPS Navigation', 'Bluetooth', 'Blind Spot Monitor', 'Lane Keep Assist', 'Wireless CarPlay', 'LED Headlights'],
		location: 'Thessaloniki',
		isAvailable: true,
		averageRating: 4.5,
		totalReviews: 27,
		mileage: 19000,
		color: 'Gray',
		licensePlate: '06HIJ456',
		carType: 'suv',
	},
	{
		brand: 'Mazda',
		modelName: 'CX-5',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 700,
		images: [
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
		],
		description: 'Stylish SUV with premium interior and smooth handling, perfect for both city and highway driving.',
		features: ['GPS Navigation', 'Bluetooth', 'Apple CarPlay', 'Blind Spot Monitor', 'Lane Departure Warning', 'Power Liftgate'],
		location: 'Heraklion',
		isAvailable: true,
		averageRating: 4.7,
		totalReviews: 33,
		mileage: 14000,
		color: 'Red',
		licensePlate: '06QRS234',
		carType: 'suv',
	},
	{
		brand: 'Kia',
		modelName: 'Sportage',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'hybrid',
		seats: 5,
		pricePerDay: 680,
		images: [
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
		],
		description: 'Modern hybrid SUV with impressive fuel economy and advanced safety features.',
		features: ['GPS Navigation', 'Bluetooth', 'Wireless Charging', 'Panoramic Sunroof', 'Highway Driving Assist', 'Smart Cruise Control'],
		location: 'Chania',
		isAvailable: true,
		averageRating: 4.6,
		totalReviews: 29,
		mileage: 16000,
		color: 'White',
		licensePlate: '35TUV567',
		carType: 'suv',
	},
	{
		brand: 'Volkswagen',
		modelName: 'Transporter',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'diesel',
		seats: 9,
		pricePerDay: 900,
		images: [
			'https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&h=600&fit=crop',
		],
		description: 'Iconic VW van perfect for large groups, surf trips, and adventures.',
		features: ['GPS Navigation', 'Bluetooth', 'Backup Camera', 'Climate Control', 'Sliding Doors', 'Ample Cargo Space'],
		location: 'Mykonos',
		isAvailable: true,
		averageRating: 4.6,
		totalReviews: 16,
		mileage: 28000,
		color: 'Orange',
		licensePlate: '34KLM789',
		carType: 'van',
	},
	{
		brand: 'Ford',
		modelName: 'Mustang',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 4,
		pricePerDay: 1800,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'Iconic American muscle car with powerful V8 engine and thrilling performance.',
		features: ['Sport Mode', 'Premium Sound', 'Track Apps', 'Launch Control', 'Selectable Drive Modes', 'Performance Package'],
		location: 'Corfu',
		isAvailable: true,
		averageRating: 4.9,
		totalReviews: 38,
		mileage: 7000,
		color: 'Blue',
		licensePlate: '34RST123',
		carType: 'sports',
	},
	{
		brand: 'Renault',
		modelName: 'Clio',
		year: 2023,
		transmission: 'manual',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 320,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'Compact and economical city car, perfect for urban driving.',
		features: ['Bluetooth', 'Air Conditioning', 'USB Ports', 'Central Locking'],
		location: 'Corfu',
		isAvailable: true,
		averageRating: 4.2,
		totalReviews: 25,
		mileage: 38000,
		color: 'White',
		licensePlate: '35UVW890',
		carType: 'hatchback',
	},
	{
		brand: 'Nissan',
		modelName: 'Qashqai',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'hybrid',
		seats: 5,
		pricePerDay: 720,
		images: [
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
		],
		description: 'Popular crossover with hybrid technology and spacious interior.',
		features: ['GPS Navigation', 'Bluetooth', 'Parking Camera', 'Lane Assist', 'ProPilot Assist', 'Bose Sound System'],
		location: 'Patras',
		isAvailable: true,
		averageRating: 4.5,
		totalReviews: 31,
		mileage: 11000,
		color: 'Black',
		licensePlate: '06XYZ123',
		carType: 'suv',
	},
	{
		brand: 'Peugeot',
		modelName: '3008',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'diesel',
		seats: 5,
		pricePerDay: 620,
		images: [
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
		],
		description: 'Stylish French SUV with distinctive design and comfortable ride.',
		features: ['GPS Navigation', 'Bluetooth', 'Grip Control', 'Panoramic Roof', 'Digital Cockpit', 'Massaging Seats'],
		location: 'Rhodes',
		isAvailable: true,
		averageRating: 4.4,
		totalReviews: 22,
		mileage: 21000,
		color: 'Gray',
		licensePlate: '34ABC456',
		carType: 'suv',
	},
	{
		brand: 'Seat',
		modelName: 'Leon',
		year: 2023,
		transmission: 'manual',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 420,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'Sporty compact car with agile handling and modern design.',
		features: ['Bluetooth', 'Digital Cockpit', 'Sports Seats', 'Cruise Control', 'LED Headlights'],
		location: 'Athens',
		isAvailable: true,
		averageRating: 4.3,
		totalReviews: 18,
		mileage: 29000,
		color: 'Orange',
		licensePlate: '35DEF789',
		carType: 'hatchback',
	},
	{
		brand: 'Skoda',
		modelName: 'Octavia',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'diesel',
		seats: 5,
		pricePerDay: 550,
		images: [
			'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop',
		],
		description: 'Practical family sedan with generous space and excellent fuel economy.',
		features: ['GPS Navigation', 'Bluetooth', 'Adaptive Cruise Control', 'Lane Assist', 'Large Boot', 'Ambient Lighting'],
		location: 'Chania',
		isAvailable: true,
		averageRating: 4.6,
		totalReviews: 34,
		mileage: 15000,
		color: 'Silver',
		licensePlate: '06GHI012',
		carType: 'sedan',
	},
	{
		brand: 'Volvo',
		modelName: 'XC60',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'hybrid',
		seats: 5,
		pricePerDay: 1250,
		images: [
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
		],
		description: 'Luxury SUV with top safety ratings and Scandinavian design.',
		features: ['GPS Navigation', 'Pilot Assist', 'Harman Kardon Audio', 'Panoramic Roof', 'Air Suspension', '360 Camera'],
		location: 'Thessaloniki',
		isAvailable: true,
		averageRating: 4.8,
		totalReviews: 27,
		mileage: 9000,
		color: 'Blue',
		licensePlate: '34JKL345',
		carType: 'luxury',
	},
	{
		brand: 'Opel',
		modelName: 'Corsa',
		year: 2023,
		transmission: 'manual',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 340,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'Small and efficient hatchback, ideal for city commuting.',
		features: ['Bluetooth', 'Air Conditioning', 'USB Charging', 'Electric Windows'],
		location: 'Santorini',
		isAvailable: true,
		averageRating: 4.1,
		totalReviews: 16,
		mileage: 33000,
		color: 'Red',
		licensePlate: '35MNO678',
		carType: 'hatchback',
	},
	{
		brand: 'Chevrolet',
		modelName: 'Camaro',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 4,
		pricePerDay: 2200,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'American muscle car with aggressive styling and powerful engine.',
		features: ['Sport Mode', 'Performance Exhaust', 'Track Mode', 'Launch Control', 'Magnetic Ride Control', 'Head-Up Display'],
		location: 'Patras',
		isAvailable: false,
		averageRating: 4.9,
		totalReviews: 19,
		mileage: 4500,
		color: 'Yellow',
		licensePlate: '34PQR901',
		carType: 'sports',
	},
	{
		brand: 'Jeep',
		modelName: 'Compass',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'diesel',
		seats: 5,
		pricePerDay: 780,
		images: [
			'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop',
		],
		description: 'Capable SUV with off-road prowess and modern amenities.',
		features: ['GPS Navigation', '4x4 System', 'Bluetooth', 'Parking Sensors', 'Selec-Terrain', 'UConnect System'],
		location: 'Heraklion',
		isAvailable: true,
		averageRating: 4.4,
		totalReviews: 24,
		mileage: 19000,
		color: 'Green',
		licensePlate: '06STU234',
		carType: 'suv',
	},
	{
		brand: 'Citroen',
		modelName: 'C4',
		year: 2023,
		transmission: 'automatic',
		fuelType: 'petrol',
		seats: 5,
		pricePerDay: 480,
		images: [
			'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop',
		],
		description: 'Comfortable compact car with unique French flair.',
		features: ['GPS Navigation', 'Bluetooth', 'Advanced Comfort Seats', 'Wireless Charging', 'Parking Camera'],
		location: 'Rhodes',
		isAvailable: true,
		averageRating: 4.3,
		totalReviews: 20,
		mileage: 24000,
		color: 'White',
		licensePlate: '35VWX567',
		carType: 'hatchback',
	},
	{
		brand: 'Lexus',
		modelName: 'ES',
		year: 2024,
		transmission: 'automatic',
		fuelType: 'hybrid',
		seats: 5,
		pricePerDay: 1400,
		images: [
			'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=800&h=600&fit=crop',
			'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop',
		],
		description: 'Premium luxury sedan with exceptional comfort and hybrid efficiency.',
		features: ['Mark Levinson Audio', 'Adaptive Cruise Control', 'Heated & Ventilated Seats', 'Panoramic Roof', 'Safety System+', 'Premium Leather'],
		location: 'Corfu',
		isAvailable: true,
		averageRating: 4.9,
		totalReviews: 26,
		mileage: 6000,
		color: 'Black',
		licensePlate: '34YZA890',
		carType: 'luxury',
	},
]

async function seedDatabase() {
	await connectDB()

	// Clear existing cars
	await Car.deleteMany({})

	// Insert new cars
	const result = await Car.insertMany(carData)

	return NextResponse.json({
		success: true,
		message: 'Database seeded successfully',
		count: result.length,
	})
}

export async function GET() {
	try {
		return await seedDatabase()
	} catch (error: any) {
		console.error('Error seeding database:', error)
		return NextResponse.json(
			{
				success: false,
				error: error.message || 'Failed to seed database',
			},
			{ status: 500 }
		)
	}
}

export async function POST() {
	try {
		return await seedDatabase()
	} catch (error: any) {
		console.error('Error seeding database:', error)
		return NextResponse.json(
			{
				success: false,
				error: error.message || 'Failed to seed database',
			},
			{ status: 500 }
		)
	}
}
